# Generated by Django 4.1 on 2022-08-08 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_level', models.CharField(choices=[('FR', 'Free'), ('BR', 'Bronze'), ('SI', 'Silver'), ('GO', 'Gold'), ('PL', 'Platinum'), ('CO', 'Contributor'), ('FO', 'Founder')], default='FR', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
