# Generated by Django 4.1 on 2022-08-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/profile_images/profile.png', upload_to='images/profile_images'),
        ),
    ]
