# Generated by Django 4.1 on 2022-08-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author_alter_article_date_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_content',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
